### ISSUE TITLE
Name Research

### ISSUE THREAD

**Issue by seejamescode** [IBM-Design/charts#1]
Preferably a historical nod to IBM in some way. Everything is fair game though!

Bonus: Promoting diversity

**Comment by joshblack** [comment]
Still a big fan of `tufte` but I understand the drawbacks 😄

**Comment by mhsenkow** [comment]
http://www.fritz-kahn.com/ - Kahn (Infographic medical/artist maybe less direct data-viz relation)

Fernanda Viégas and Martin Wattenberg (Creators of Many Eyes which contributed to what became watson analytics) - VW? ViegaWat?.... (The name doesn't seem super easy to work with.

**Comment by seejamescode** [comment]
Any objection to maintaining literalness with `@ibm-design/charts`?

**Comment by joshblack** [comment]
Works for me 👍

**Comment by mhsenkow** [comment]
I need to get faster with checking htese but yeah, seems good not really a fan of rando code names

**Comment by seejamescode** [comment]
Always okay to reopen these if you miss the chance!
