### ISSUE TITLE
Initial 1.0 Milestone Planning

### ISSUE THREAD

**Issue by joshblack** [IBM-Design/charts#12]
We have approximately six, two-week sprints currently planned for this milestone, although this definitely can change as needed. I figured we could categorize the existing chart models in terms of levels of complexity in order to make each sprint balanced in terms of goals. As a first attempt, here's what I'm thinking:

Level 1:

- Bar chart
- Line chart
- Stacked bar chart
- Piechart
- Scatterplot
- Heatmap

Level 2:

- Treemap
- Map
- Flows
- Bubble chart
- Radar

Level 3:

- Network

## Sprint Planning

Assuming the current deadline, here's how we could break up the current work in terms of chart deliverables:

Sprint 1:

- [ ] Bar chart
- [ ] Line chart

Sprint 2:

- [ ] Stacked bar chart
- [ ] Treemap

Sprint 3:

- [ ] Piechart
- [ ] Map

Sprint 4:

- [ ] Scatterplot
- [ ] Flows

Sprint 5:

- [ ] Heatmap
- [ ] Bubble chart

Sprint 6:

- [ ] Radar
- [ ] Network

In addition to delivering on the charts directly, we'll also have to be aware of documentation and usage examples of the existing charts. We also should try and actively recruit contributors for existing implementations, as well as shepherds for framework/library-level implementations.

Thoughts?

**Comment by seejamescode** [comment]
Genius. If we are saying that a React release will be ready at the end of each sprint, should we line-up design specs for each sprint ahead?

**Comment by joshblack** [comment]
I think we can definitely aim for some simplistic versions of each chart at the end of each sprint, ready to be used for simple use cases. I think as we explore more interaction-based and animation-driven visualizations the complexity will grow accordingly. For this first set though, I think just making them work with data is a great first step.

Lining the design specs up before each sprint would be awesome. Ideally, we'd have the files so that designers on the same teams could leverage the assets so that the two groups are in sync.

**Comment by mhsenkow** [comment]
Can I push for a donut chart in there either in conjunction or in replacement of the pie-chart? https://eagereyes.org/blog/2016/an-illustrated-tour-of-the-pie-chart-study-results

**Comment by seejamescode** [comment]
@mhsenkow I need you to get that added to the IBM Design Language repo too for https://www.ibm.com/design/language/experience/data-visualization/chart-models/. For now, we could make the pie chart and then it would be a visual circle hiding the center?

**Comment by mhsenkow** [comment]
Yes/or the pie chart could be made to contain both an inner and outer radius. I believe coding them that way when we get to them will also prevent problems for potential transitions/animations later.

**Comment by seejamescode** [comment]
Hey @joshblack, the sprint charts do not represent each level of charts chronologically. Was that intentional?

**Comment by joshblack** [comment]
I figured we should aim for having some combination of level 1 / level 2 chart each sprint (the levels correspond to perceived implementation difficulty).
