### ISSUE TITLE
Yarn Watch Fails

### ISSUE THREAD

**Issue by seejamescode** [IBM-Design/charts#17]
**Do you want to request either a *feature or user story*, or report a *bug*?**
Bug

**What is the current behavior?**
`yarn test -- --watch` fails after previous steps in readme. I have Node v6.9.1 installed.

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via https://jsfiddle.net or similar (template: https://jsfiddle.net/reactjs/69z2wepo/).**

```
Determining test suites to run...2017-01-12 18:54 node[3468] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-01-12 18:54 node[3468] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
2017-01-12 18:54 node[3468] (FSEvents.framework) FSEventStreamStart: register_with_server: ERROR: f2d_register_rpc() => (null) (-22)
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: Error watching file for changes: EMFILE
    at exports._errnoException (util.js:1026:11)
    at FSEvent.FSWatcher._handle.onchange (fs.js:1406:11)
error Command failed with exit code 1.
info Visit http://yarnpkg.com/en/docs/cli/test for documentation about this command.
```

**What is the expected behavior?**
Get to work on the project!

**Comment by joshblack** [comment]
I think this is something `watchman` related. Try:

```bash
brew uninstall watchman
brew link automake
brew install --HEAD watchman
```

**Comment by seejamescode** [comment]
Yeah, no watchman installed. I will add that to the readme before closing this.
