### ISSUE TITLE
What technology to utilize?

### ISSUE THREAD

**Issue by seejamescode** [IBM-Design/charts#2]
The choice should be based on:

- Current open-source support
- Impact on current IBM offerings
- Enables a speedy 1.0 release

**Comment by seejamescode** [comment]
We want this to be able to spit out the examples provided! 😃

**Comment by joshblack** [comment]
Default ones will probably be the Vanilla JS implementation that is lead by the accurat group. In addition, will probably support React as there is a shepherd for that implementation (myself in the Watson Horizontal Apps group).

If other groups are interested, should definitely identify other shepherds for language implementations that we can include.
