### ISSUE TITLE
Stacked bar chart visual specs

### ISSUE THREAD

**Issue by seejamescode** [IBM-Design/charts#21]

**Comment by winslet** [comment]
Reference page: https://www.ibm.com/design/language/experience/data-visualization/chart-models/stacked-barchart/

**Comment by winslet** [comment]
Started to have a play: 
![image](https://cloud.githubusercontent.com/assets/13980028/21985727/0e04a3f0-dbf4-11e6-8d85-6ffc533ba366.png)

![image](https://cloud.githubusercontent.com/assets/13980028/21985735/154997c4-dbf4-11e6-8cc9-8355c4f3edf8.png)

For the second image (% based data) a couple of questions: 
1. Colour accessibility - do we need to differentiate by texture along with colour?
2. Hover states - are there designs for these anywhere?
3. Would the hover state also change the colours? eg:
![image](https://cloud.githubusercontent.com/assets/13980028/21985864/afc1a56c-dbf4-11e6-8ee7-8e0dfc6d8ad1.png)

@hchughes is there any guidance for the above?

**Comment by winslet** [comment]
Further thoughts on colours for point 1 above - using hue's instead of different colours: 

![image](https://cloud.githubusercontent.com/assets/13980028/21986292/b7d448fc-dbf6-11e6-99c6-607dbbd88227.png)

However we may need to change the legend in order to be able to differentiate the colours (eg make the colour spot larger). Thoughts?

**Comment by seejamescode** [comment]
We will ask about hover and focus states on our call tomorrow!

**Comment by seejamescode** [comment]
Awesome work so far!

**Comment by winslet** [comment]
I've discovered a bunch of useful stuff on the new site here: https://www.ibm.com/design/language/experience/data-visualization/interaction/ 

for example, basic hover: 
![image](https://cloud.githubusercontent.com/assets/13980028/21991740/b35f9776-dc0b-11e6-9c95-01c2fd98a45e.png)

and selected states: 
![image](https://cloud.githubusercontent.com/assets/13980028/21991747/c1952bc6-dc0b-11e6-9093-fd4ffec3e484.png)

things to work on for both:
1. Hover states with complex data values shown. (eg Value + other relevant info)
2. How the selected states fit on mobile sized graphs 👍 

Also more suggested colour palettes here: https://www.ibm.com/design/language/resources/color-library/#data-viz-starter-palettes 💯

**Comment by seejamescode** [comment]
I am okay with the simple example you provided showing the value. 

Just talked to @evanmaeda and we both agree that the selected state could be more "IBM Design Language". I will make an issue for that visual problem. No worries to nock out that interaction now.

No matter what, the hover and focused state should be the same interaction.
