### ISSUE TITLE
Visual specs template file

### ISSUE THREAD

**Issue by seejamescode** [IBM-Design/charts#23]
This will enable multiple visual designers to contribute to IBM Design Charts. We are already seeking a Sketch visual spec file for each chart type. If there was a starter file, a new visual designer could work on these many future issues.

@winslet, would you be down to take this one first for us?

**Comment by winslet** [comment]
@seejamescode yup ill take this one on, 

As a template I will start by bringing the grids over from Illustrator (which is its current form) and the colour guidance too. If you have any further ideas of what content you think would be useful then could you drop it below 👍

**Comment by winslet** [comment]
### Base chart grid and guidelines available here: https://ibm.box.com/s/gpu7l4qexvm1vw7z73fh4g9pwbobdf76
 

Document provides base guidance for the following:
![image](https://cloud.githubusercontent.com/assets/13980028/21984287/29f62630-dbed-11e6-969f-3b90b4b494f6.png)

eg:
![image](https://cloud.githubusercontent.com/assets/13980028/21984321/493bf0ba-dbed-11e6-9b56-bdb9e526a934.png)
![image](https://cloud.githubusercontent.com/assets/13980028/21984327/520fb104-dbed-11e6-86cd-ec06f56d45c5.png)
![image](https://cloud.githubusercontent.com/assets/13980028/21984332/590333aa-dbed-11e6-9160-f228fac79a8c.png)

@seejamescode how would you like to share that file out? and start to break down the workload? There are multiple graphs which are more fluid (eg Map https://ibm.com/design/language/experience/data-visualization/chart-models/map/) which will custom creation for each one, just so we are aware. 

Next steps at this point? It shouldnt be too difficult to get something mocked up for the majority of the graph styles having dug into this now.

**Comment by seejamescode** [comment]
Thanks @winslet! Can we include 320px width artboards also for mobile?

I can either upload a `visual` or `specs` folder *or* place each sketch file in the appropriate chart folder on this repo. Which would you prefer?

Also, do you have git experience to make updates to them?

**Comment by matthewgallo** [comment]
Hey @winslet!! Just wanted to give you a heads up that the idl-data-viz.w3ibm.mybluemix.net/design/language url won't exist anymore. Everything that was there is now on the public site, www.ibm.com/design/language.

**Comment by winslet** [comment]
@matthewgallo thanks for the heads up - ill get those links updated 👍 

@seejamescode im not finding any guidance on viz for mobile devices atm - which I would imagine was discussed at an earlier stage, @hchughes did Accurat look into mobile visualisations at all?

**Comment by seejamescode** [comment]
Accurat did not believe the tech for mobile charts is ready yet, but we are hear to break that thought down. :)

Hopefully, it is a matter of components only changing layout. However, you are free to do what you believe is best for those users.

**Comment by winslet** [comment]
File update with the above changes, new links etc (minus the mobile view - we can discuss this tomorrow) https://ibm.box.com/s/gpu7l4qexvm1vw7z73fh4g9pwbobdf76
