### ISSUE TITLE
Conduct Audit of IBM Product Portfolio Visualization Requirements

### ISSUE THREAD

**Issue by joshblack** [IBM-Design/charts#32]
Right now we're reaching out to the following organizations to understand their requirements:

- [ ] Watson
  - [x] Company Analyzer
  - [x] Virtual Agent
  - [x] Horizontal Apps
- [ ] Watson Analytics
- [ ] Bluemix
  - [ ] Monitoring
- [ ] IoT
- [x] Design (NPS)

**Comment by joshblack** [comment]
Virtual Agent: https://ibm.box.com/s/1czwwr60xzcenrvt0slrwcui15vbnrka

Company Analyzer: https://ibm.box.com/s/ena1bnmwbgdbyfof3lm61qu7dqc34z37

**Comment by seejamescode** [comment]
NPS is looking for:
- Line
- Treemap
- Scatterplot
- Stacked area chart
