### ISSUE TITLE
charts-colors

### ISSUE THREAD

**Issue by seejamescode** [IBM-Design/charts#35]
A developer needs to be able to import this package into their chart file and call pre-defined color palettes.

**Comment by photodow** [comment]
Do we have any context to this issue? Any preferred way we'd like to access those color palettes, or do we even have those color palettes defined yet (use IDL I assume?)?

**Comment by seejamescode** [comment]
Yeah, the first two palettes to start with are on the IDL site:
https://www.ibm.com/design/language/resources/color-library/

This package should import `ibm-design-colors` to come up with the package.

Here is an example of where I should be able to use the package, but had to manually specify the colors: https://github.com/IBM-Design/charts/blob/master/packages/charts-react-line/src/LineChart.js#L46-L55

Here is the example of what we were envisioning:
https://github.com/IBM-Design/charts/pull/26#issuecomment-274098486
