### ISSUE TITLE
charts-react-line

### ISSUE THREAD

**Issue by seejamescode** [IBM-Design/charts#37]
We should get a lines branch going for this work!

**Comment by sabov** [comment]
Hey @seejamescode, could you make a breakdown into subtasks?

**Comment by seejamescode** [comment]
- [ ] Min and max of axis - James
- [x] Background grid, axis, and points that respond to an`intervals` prop
- [x] Legend component
- [ ] Animation detailed on [IDL](https://www.ibm.com/design/language/experience/data-visualization/animation/)
- [ ]  Responsiveness (width: 100%)

Match specs detailed at https://github.com/IBM-Design/charts/blob/master/packages/charts-design/IBM-Design-Charts_Line.sketch

**Comment by seejamescode** [comment]
Made a branch for us to work with for this: https://github.com/IBM-Design/charts/tree/charts-react-line

**Comment by seejamescode** [comment]
Shelving for c3 implementations
