### ISSUE TITLE
Get official Design specs

### ISSUE THREAD

**Issue by joshblack** [IBM-Design/charts#9]
In order to start working on the implementation of each chart, we're going to need official design resources to make sure that we're matching the latest version of the design language charts.

What process are we going to follow for this, and who are the points of contact for managing this from a design perspective?

cc @seejamescode

**Comment by evanmaeda** [comment]
@joshblack I would start with this resource around the chart grid, which is located as a download on this page: http://idl-data-viz.w3ibm.mybluemix.net/design/language/experience/data-visualization/chart-models/

Lets follow up and chat about the other design resources in the near future.

**Comment by joshblack** [comment]
Totally, I agree that's probably the best place to start!

**Comment by seejamescode** [comment]
Meeting on Jan 17th, 2017 should resolve this.

**Comment by seejamescode** [comment]
@winslet got these!
